# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Wajir_ICGS
                                 A QGIS plugin
 A plugin for fetching data collected in the field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by LocateIT, Kevin Kiprotich
        email                : kevinkiprotich0089@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtWidgets import QAction, QApplication, QMenu, QMessageBox
from .questionnaire import DlgQuestionnaire
from .data_collection import DlgDataCollection
from .settings import DlgSettings
from .share import DlgShare

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .wajir_icgs_dialog import Wajir_ICGSDialog
import os.path


class Wajir_ICGS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Wajir_ICGS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&WAJIR ICGS')
        self.dlg_settings = DlgSettings()
        self.dlg_questionniare = DlgQuestionnaire()
        self.dlg_data_collection = DlgDataCollection()
        self.dlg_share = DlgShare()

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Wajir_ICGS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        self.add_action(
            ':/plugins/wajir_icgs/icons/gear.svg',
            text=QApplication.translate('Wajir ICGS', u'ICGS User Settings'),
            callback=self.run_settings,
            parent=self.iface.mainWindow(),
            status_tip=QApplication.translate('Wajir ICGS', 'ICGS User Settings'))
        
        self.add_action(
            ':/plugins/wajir_icgs/icons/add_form.svg',
            text=QApplication.translate('Wajir ICGS', u'Create a questionnaire'),
            callback=self.run_questionnaire,
            parent=self.iface.mainWindow(),
            status_tip=QApplication.translate('Wajir ICGS', 'Create a questionnaire'))
        
        self.add_action(
            ':/plugins/wajir_icgs/icons/share.svg',
            text=QApplication.translate('Wajir ICGS', u'Share a questionnaire'),
            callback=self.run_share,
            parent=self.iface.mainWindow(),
            status_tip=QApplication.translate('Wajir ICGS', 'Share a questionnaire'))
        
        self.add_action(
            ':/plugins/wajir_icgs/icons/smartphone.svg',
            text=QApplication.translate('Wajir ICGS', u'ICGS Data collection'),
            callback=self.run_collection,
            parent=self.iface.mainWindow(),
            status_tip=QApplication.translate('Wajir ICGS', 'ICGS Data collection'))

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&WAJIR ICGS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run_settings(self):
        self.dlg_settings.show()
        result = self.dlg_settings.exec_()

    def run_questionnaire(self):
        self.dlg_questionniare.show()
        result = self.dlg_questionniare.exec_()

    def run_collection(self):
        self.dlg_data_collection.show()
        result = self.dlg_data_collection.exec_()
    
    def run_share(self):
        self.dlg_share.show()
        result = self.dlg_share.exec_()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = Wajir_ICGSDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
