# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgQuestionnaireDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgQuestionnaireDetails(object):
    def setupUi(self, DlgQuestionnaireDetails):
        DlgQuestionnaireDetails.setObjectName("DlgQuestionnaireDetails")
        DlgQuestionnaireDetails.resize(306, 325)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgQuestionnaireDetails.sizePolicy().hasHeightForWidth())
        DlgQuestionnaireDetails.setSizePolicy(sizePolicy)
        DlgQuestionnaireDetails.setMaximumSize(QtCore.QSize(16777215, 500))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgQuestionnaireDetails)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DlgQuestionnaireDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.qrLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qrLabel.sizePolicy().hasHeightForWidth())
        self.qrLabel.setSizePolicy(sizePolicy)
        self.qrLabel.setMinimumSize(QtCore.QSize(230, 230))
        self.qrLabel.setMaximumSize(QtCore.QSize(230, 230))
        self.qrLabel.setText("")
        self.qrLabel.setPixmap(QtGui.QPixmap("../icon.png"))
        self.qrLabel.setObjectName("qrLabel")
        self.verticalLayout.addWidget(self.qrLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.linkLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkLabel.sizePolicy().hasHeightForWidth())
        self.linkLabel.setSizePolicy(sizePolicy)
        self.linkLabel.setWordWrap(True)
        self.linkLabel.setObjectName("linkLabel")
        self.horizontalLayout.addWidget(self.linkLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(DlgQuestionnaireDetails)
        QtCore.QMetaObject.connectSlotsByName(DlgQuestionnaireDetails)

    def retranslateUi(self, DlgQuestionnaireDetails):
        _translate = QtCore.QCoreApplication.translate
        DlgQuestionnaireDetails.setWindowTitle(_translate("DlgQuestionnaireDetails", "Questionniare Details"))
        self.groupBox.setTitle(_translate("DlgQuestionnaireDetails", "Questionniare Details"))
        self.label.setText(_translate("DlgQuestionnaireDetails", "Scan the QR-code below"))
        self.label_2.setText(_translate("DlgQuestionnaireDetails", "Copy link: "))
        self.linkLabel.setText(_translate("DlgQuestionnaireDetails", "link"))
